### ISSUE TITLE
Register same JsonDiscriminatorAttribute results in exception

### ISSUE THREAD

**Issue by ae84** [dahomey-technologies/Dahomey.Json#108]
Hello, i'm using your library to serialize/deserialize inherited classes.
In one area i've a DTO pretty similar to another one that must use the same discriminator of the original one but this seems to be a problem because it throws a runtime exception saying that **an item with the same key has already been added**

I'm adding the [JsonDiscriminatorAttribute("TheDuplicatedKeyImTryingToAdd")] decorator on top of the class definition.

From my understading the problem is releated to the fact that it does not expect to have the same Key added twice on different classes ( actually the class name is the same  but it lives in another namespace ), something like:

- DTO1 full qualification -> DTOS.Shared.MyDtoName
- DTO2 full qualification -> DTOS.ControllerName.ActionName.Response.MyDtoName

I think that the library behavior is by design but is there a way to overcome this problem?

here the exception:

```
Message: An item with the same key has already been added. Key: TheDuplicatedKeyImTryingToAdd
Source: System.Private.CoreLib 
Stack:    at System.Collections.Generic.Dictionary`2.TryInsert(TKey key, TValue value, InsertionBehavior behavior)
   at System.Collections.Generic.Dictionary`2.Add(TKey key, TValue value)
   at Dahomey.Json.Serialization.Conventions.DefaultDiscriminatorConvention`1.TryRegisterType(Type type)
   at Dahomey.Json.Serialization.Conventions.DiscriminatorConventionRegistry.<>c__DisplayClass15_0.b__0(IDiscriminatorConvention c)
   at System.Linq.Enumerable.TryGetFirst[TSource](IEnumerable`1 source, Func`2 predicate, Boolean& found)
   at Dahomey.Json.Serialization.Conventions.DiscriminatorConventionRegistry.InternalGetConvention(Type type)
   at Dahomey.Json.Serialization.Conventions.DiscriminatorConventionRegistry.b__11_0(Type t)
   at System.Collections.Concurrent.ConcurrentDictionary`2.GetOrAdd(TKey key, Func`2 valueFactory)
   at Dahomey.Json.Serialization.Conventions.DiscriminatorConventionRegistry.GetConvention(Type type)
   at Dahomey.Json.Serialization.Converters.ObjectConverter`1..ctor(JsonSerializerOptions options) 
```

Thanks for you collaboration.

**Comment by ae84** [comment]
Digging more into your code i understood that the question had no meaning, the problem need to be solved outside your librabry.
