### ISSUE TITLE
Problem serializing and deserializing objects with IDictionary properties annotated with JsonExtensionData

### ISSUE THREAD

**Issue by snorremd** [dahomey-technologies/Dahomey.Json#33]
There is an issue when calling `JsonSerializer.Serialize(someObject)` when that object is instantiated from a type that contains an `IDictionary<string, object>` property with a `JsonExtensionData` annotation. I encountered this issue as I return a [ProblemDetails](https://docs.microsoft.com/en-us/dotnet/api/microsoft.aspnetcore.mvc.problemdetails?view=aspnetcore-3.1) instance in my API. The problem does not happen when using `System.Text.Json` without the Dahomey.Json extensions enabled.

See the following example:

```csharp
public class Test {
        public class WeatherForecastWithExtensionDataAndIDictionary
        {
            public DateTimeOffset Date { get; set; }
            public int TemperatureCelsius { get; set; }
            public string Summary { get; set; }
            [JsonExtensionData]
            public IDictionary<string, object> ExtensionData { get; set; }
        }
        
        [Fact]
        public void TestWrite()
        {
            JsonSerializerOptions options = new JsonSerializerOptions();
            options.SetupExtensions();

            const string json = @"{""Date"":""2019-08-01T00:00:00-07:00"",""TemperatureCelsius"":25,""Summary"":""Hot"",""DatesAvailable"":[""2019-08-01T00:00:00-07:00"",""2019-08-02T00:00:00-07:00""],""SummaryWords"":[""Cool"",""Windy"",""Humid""]}";
            var weatherForecast = new WeatherForecastWithExtensionDataAndIDictionary()
            {
                Summary = "Hot",
                Date = DateTimeOffset.Parse("2019-08-01T00:00:00-07:00"),
                TemperatureCelsius = 25,
                ExtensionData = new Dictionary<string, object>()
                {
                    {"SummaryWords", new List<string>() {"Cool, Windy, Humid"}}
                }
            };
            var serialized = JsonSerializer.Serialize(weatherForecast, options);

            Assert.Equal(json, serialized);

        }

}

```

The `Serialize` call with Dahomey extensions enabled will cause the following exception:

```csharp
System.Text.Json.JsonException : Invalid Serialization DataExtension Property
   at Dahomey.Json.Serialization.Converters.Mappings.ObjectMapping`1.MapExtensionData(PropertyInfo propertyInfo) in /Users/snorre/workspaces/Dahomey.Json/src/Dahomey.Json/Serialization/Converters/Mappings/ObjectMapping.cs:line 110
   at Dahomey.Json.Serialization.Converters.Mappings.DefaultObjectMappingConvention.Apply[T](JsonSerializerOptions options, ObjectMapping`1 objectMapping) in /Users/snorre/workspaces/Dahomey.Json/src/Dahomey.Json/Serialization/Converters/Mappings/DefaultObjectMappingConvention.cs:line 54
   at Dahomey.Json.Serialization.Converters.Mappings.ObjectMapping`1.AutoMap() in /Users/snorre/workspaces/Dahomey.Json/src/Dahomey.Json/Serialization/Converters/Mappings/ObjectMapping.cs:line 50
   at Dahomey.Json.Serialization.Converters.Mappings.ObjectMapping`1.Dahomey.Json.Serialization.Converters.Mappings.IObjectMapping.AutoMap() in /Users/snorre/workspaces/Dahomey.Json/src/Dahomey.Json/Serialization/Converters/Mappings/ObjectMapping.cs:line 44
   at Dahomey.Json.Serialization.Converters.Mappings.ObjectMappingRegistry.CreateDefaultObjectMapping(Type type) in /Users/snorre/workspaces/Dahomey.Json/src/Dahomey.Json/Serialization/Converters/Mappings/ObjectMappingRegistry.cs:line 72
   at Dahomey.Json.Serialization.Converters.Mappings.ObjectMappingRegistry.<>c__DisplayClass7_0.<Lookup>b__0(Type t) in /Users/snorre/workspaces/Dahomey.Json/src/Dahomey.Json/Serialization/Converters/Mappings/ObjectMappingRegistry.cs:line 57
   at System.Collections.Concurrent.ConcurrentDictionary`2.GetOrAdd(TKey key, Func`2 valueFactory)
   at Dahomey.Json.Serialization.Converters.Mappings.ObjectMappingRegistry.Lookup(Type type) in /Users/snorre/workspaces/Dahomey.Json/src/Dahomey.Json/Serialization/Converters/Mappings/ObjectMappingRegistry.cs:line 57
   at Dahomey.Json.Serialization.Converters.Mappings.ObjectMappingRegistry.Lookup[T]() in /Users/snorre/workspaces/Dahomey.Json/src/Dahomey.Json/Serialization/Converters/Mappings/ObjectMappingRegistry.cs:line 52
   at Dahomey.Json.Serialization.Converters.ObjectConverter`1..ctor(JsonSerializerOptions options) in /Users/snorre/workspaces/Dahomey.Json/src/Dahomey.Json/Serialization/Converters/ObjectConverter.cs:line 85

```

I have created [a fork with reproduction of the issue in tests](https://github.com/snorremd/Dahomey.Json/blob/master/src/Dahomey.Json.Tests/Issues/Issue0033.cs).

**Comment by snorremd** [comment]
Thank you for the very quick response and fix. Much appreciated!

I've got a secondary issue now that is related to the ProblemDetails class,  namely that the Dictionary property does not have a `set` method. The Dahomey.Json implementation in [`ExtensionDataMemberConverter`](https://github.com/dahomey-technologies/Dahomey.Json/blob/master/src/Dahomey.Json/Serialization/Converters/ExtensionDataMemberConverter.cs#L34) checks for and uses the setter method when deserializing a property marked with the [JsonExtensionData] attribute.

I don't think this counts as a bug with your Dahomey.Json library, though I'd be interested in whether you would consider supporting such cases in the library or if you have any suggestions on a workaround.

**Comment by mcatanzariti** [comment]
Please open an new issue for a new problem
