### ISSUE TITLE
Discriminator convention not working if declaring type is object

### ISSUE THREAD

**Issue by BjornDeRijcke** [dahomey-technologies/Dahomey.Json#35]
If you have a property where the type is object, discriminator conventions are ignored.
Discriminator does not appear in the json, and reading in json (even with a discriminator present) always results in a JsonNode.

This is because the BaseObjectConverter (which is used if type is object) has no check for discriminator conventions.

Example code:
```
        [JsonDiscriminator("OrgIf")]
        public class OrganisationInfo
        {
            public string ComapnyName { get; set; }
            public string VATNumber { get; set; }

            public override string ToString()
            {
                return $"OrganisationInfo: Name={ComapnyName}, Vat={VATNumber}";
            }
        }

        [JsonDiscriminator("PersIf")]
        public class PersonInfo
        {
            public string FirstName { get; set; }
            public string LastName { get; set; }

            public override string ToString()
            {
                return $"PersonInfo: Firstname={FirstName}, Lastname={LastName}";
            }
        }

        public class ContactHolder
        {
            public bool InFavorites { get; set; }
            public object ContactInfo { get; set; }

            public override string ToString()
            {
                return $"ContactHolder: InFavorites={InFavorites}, Contact={ContactInfo}";
            }
        }
```
If you create a contactHolder instance with either OrganisationInfo or PersonInfo this discriminator is not added to the Json. And json with the discriminator present is still read as JsonNode

**Comment by izzycoding** [comment]
I have seen this issue also.
Tried to get around it by using an pseudo abstract class.
But that fails with an error about the DefaultDiscriminatorConvention adding a discriminator that already exists.

```
[JsonDiscriminator("my-base")]
public abstract class MyBase
{
}

[JsonDiscriminator("item-one")]
public class ItemOne
{
  // ... some properties ...
}

[JsonDiscriminator("item-two")]
public class ItemTwo
{
  // ... some different properties ...
}

public void DoStuff()
{
  // ... create my "testType" that has a property of MyBase
  var json = JsonSerializer.Serialize<MyTestType>(testType, options); // error here
}
```

Error I get is:
```
Exception has been thrown by the target of an invocation.
at System.ThrowHelper.ThrowAddingDuplicateWithKeyArgumentException[T](T key)
   at System.Collections.Generic.Dictionary`2.TryInsert(TKey key, TValue value, InsertionBehavior behavior)
   at System.Collections.Generic.Dictionary`2.Add(TKey key, TValue value)
   at Dahomey.Json.Serialization.Conventions.DefaultDiscriminatorConvention`1.TryRegisterType(Type type)
   at Dahomey.Json.Serialization.Conventions.DiscriminatorConventionRegistry.<>c__DisplayClass15_0.<InternalGetConvention>b__0(IDiscriminatorConvention c)
   at System.Linq.Enumerable.TryGetFirst[TSource](IEnumerable`1 source, Func`2 predicate, Boolean& found)
   at Dahomey.Json.Serialization.Conventions.DiscriminatorConventionRegistry.InternalGetConvention(Type type)
   at Dahomey.Json.Serialization.Conventions.DiscriminatorConventionRegistry.<GetConvention>b__11_0(Type t)
   at System.Collections.Concurrent.ConcurrentDictionary`2.GetOrAdd(TKey key, Func`2 valueFactory)
   at Dahomey.Json.Serialization.Conventions.DiscriminatorConventionRegistry.GetConvention(Type type)
   at Dahomey.Json.Serialization.Converters.ObjectConverter`1..ctor(JsonSerializerOptions options)
```

**Comment by mcatanzariti** [comment]
@BjornDeRijcke, Sorry it's not supported, you should use an abstract class as suggested by @izzycoding 

@izzycoding, you should not decorate the abstract class with a discriminator because it will never be instantiated. The class as a base class is automatically added to the discriminator convention. It's why you got the exception.

Please check the following test file for an example:
https://github.com/dahomey-technologies/Dahomey.Json/blob/master/src/Dahomey.Json.Tests/DiscriminatorTests.cs
