### ISSUE TITLE
"Invalid Serialization DataExtension Property" exception for ASP.NET Core types

### ISSUE THREAD

**Issue by SiggyBar** [dahomey-technologies/Dahomey.Json#41]
I am using polymorphic [model binding](https://docs.microsoft.com/en-us/aspnet/core/mvc/models/model-binding?view=aspnetcore-3.1) with `Dahomey.Json` for an ASP.NET Core Web Application, and it works great!  Except for when the JSON is invalid.  Then instead of getting a "400 Bad Request" response with a body like this:

```json
{
    "errors": {
        "": [
            "Invalid character after parsing property name. Expected ':' but got: \". Path '', line 2, position 17."
        ]
    },
    "type": "https://tools.ietf.org/html/rfc7231#section-6.5.1",
    "title": "One or more validation errors occurred.",
    "status": 400,
    "traceId": "|a02197b7-4f14b64f2613be48."
}
```

I instead get a "500 Internal Server Error" with body:

```
System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation.
---> System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation.
---> System.Text.Json.JsonException: Invalid Serialization DataExtension Property
   at Dahomey.Json.Serialization.Converters.ExtensionDataMemberConverter`3..ctor(PropertyInfo propertyInfo, JsonSerializerOptions options)
   --- End of inner exception stack trace ---
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor, Boolean wrapExceptions)
   at System.Reflection.RuntimeConstructorInfo.Invoke(BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at System.RuntimeType.CreateInstanceImpl(BindingFlags bindingAttr, Binder binder, Object[] args, CultureInfo culture)
   at System.Activator.CreateInstance(Type type, BindingFlags bindingAttr, Binder binder, Object[] args, CultureInfo culture, Object[] activationAttributes)
   at System.Activator.CreateInstance(Type type, Object[] args)
   at Dahomey.Json.Serialization.Converters.Mappings.ObjectMapping`1.MapExtensionData(PropertyInfo propertyInfo)
   at Dahomey.Json.Serialization.Converters.Mappings.DefaultObjectMappingConvention.Apply[T](JsonSerializerOptions options, ObjectMapping`1 objectMapping)
   at Dahomey.Json.Serialization.Converters.Mappings.ObjectMapping`1.AutoMap()
   at Dahomey.Json.Serialization.Converters.Mappings.ObjectMapping`1.Dahomey.Json.Serialization.Converters.Mappings.IObjectMapping.AutoMap()
   at Dahomey.Json.Serialization.Converters.Mappings.ObjectMappingRegistry.CreateDefaultObjectMapping(Type type)
   at Dahomey.Json.Serialization.Converters.Mappings.ObjectMappingRegistry.<>c__DisplayClass7_0.<Lookup>b__0(Type t)
   at System.Collections.Concurrent.ConcurrentDictionary`2.GetOrAdd(TKey key, Func`2 valueFactory)
   at Dahomey.Json.Serialization.Converters.Mappings.ObjectMappingRegistry.Lookup(Type type)
   at Dahomey.Json.Serialization.Converters.Mappings.ObjectMappingRegistry.Lookup[T]()
   at Dahomey.Json.Serialization.Converters.ObjectConverter`1..ctor(JsonSerializerOptions options)
   --- End of inner exception stack trace ---
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor, Boolean wrapExceptions)
   at System.Reflection.RuntimeConstructorInfo.Invoke(BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at System.RuntimeType.CreateInstanceImpl(BindingFlags bindingAttr, Binder binder, Object[] args, CultureInfo culture)
   at System.Activator.CreateInstance(Type type, BindingFlags bindingAttr, Binder binder, Object[] args, CultureInfo culture, Object[] activationAttributes)
   at System.Activator.CreateInstance(Type type, Object[] args)
   at Dahomey.Json.Serialization.Converters.Factories.AbstractJsonConverterFactory.CreateConverter(JsonSerializerOptions options, Type converterType)
   at Dahomey.Json.Serialization.Converters.Factories.AbstractJsonConverterFactory.CreateGenericConverter(JsonSerializerOptions options, Type genericType, Type[] typeArguments)
   at Dahomey.Json.Serialization.Converters.Factories.ObjectConverterFactory.CreateConverter(Type typeToConvert, JsonSerializerOptions options)
   at System.Text.Json.JsonSerializerOptions.GetConverter(Type typeToConvert)
   at System.Text.Json.JsonClassInfo.GetClassType(Type type, JsonSerializerOptions options)
   at System.Text.Json.JsonClassInfo..ctor(Type type, JsonSerializerOptions options)
   at System.Text.Json.JsonSerializerOptions.GetOrAddClass(Type classType)
   at System.Text.Json.WriteStackFrame.Initialize(Type type, JsonSerializerOptions options)
   at System.Text.Json.JsonSerializer.WriteAsyncCore(Stream utf8Json, Object value, Type inputType, JsonSerializerOptions options, CancellationToken cancellationToken)
   at Microsoft.AspNetCore.Mvc.Formatters.SystemTextJsonOutputFormatter.WriteResponseBodyAsync(OutputFormatterWriteContext context, Encoding selectedEncoding)
   at Microsoft.AspNetCore.Mvc.Formatters.SystemTextJsonOutputFormatter.WriteResponseBodyAsync(OutputFormatterWriteContext context, Encoding selectedEncoding)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeNextResultFilterAsync>g__Awaited|29_0[TFilter,TFilterAsync](ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Rethrow(ResultExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.ResultNext[TFilter,TFilterAsync](State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.InvokeResultFilters()
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeNextResourceFilter>g__Awaited|24_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Rethrow(ResourceExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.InvokeFilterPipelineAsync()
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Logged|17_1(ResourceInvoker invoker)
   at Microsoft.AspNetCore.Routing.EndpointMiddleware.<Invoke>g__AwaitRequestTask|6_0(Endpoint endpoint, Task requestTask, ILogger logger)
   at Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware.Invoke(HttpContext context)

HEADERS
=======
Accept: */*
Accept-Encoding: gzip, deflate, br
Cache-Control: no-cache
Connection: keep-alive
Content-Length: 9481
Content-Type: application/json
Host: localhost:63452
User-Agent: PostmanRuntime/7.25.0
Postman-Token: 2d7b1776-040b-4b2f-be58-0ea6e25ef56d
```

Obviously this is way less useful to the poor API user who has to figure out what is wrong.

I have narrowed the problem down to this example that uses the [ProblemDetails](https://docs.microsoft.com/en-us/dotnet/api/microsoft.aspnetcore.mvc.problemdetails?view=aspnetcore-3.1) class:

```C#
JsonSerializerOptions options = new JsonSerializerOptions();
//options.SetupExtensions();

object value = new ProblemDetails() { Status = 400 };

string result = JsonSerializer.Serialize(value, value.GetType(), options);
```

When I run this code, `result` will have the expected value `{"status":400}`.  However, when I comment in `options.SetupExtensions();`, then the Serialize() call throws the same exception as above in `Dahomey.Json.Serialization.Converters.ExtensionDataMemberConverter()`.  I would not expect calling SetupExtensions() to make a difference here.

Unfortunately, I cannot use a workaround like described in #33 (or at least I am not aware of how to do that), because the [ValidationProblemDetails](https://docs.microsoft.com/en-us/dotnet/api/microsoft.aspnetcore.mvc.validationproblemdetails?view=aspnetcore-3.1) gets created outside of my control by ASP.NET Core itself.

**Comment by SiggyBar** [comment]
This works now, thank you so much 😃
