### ISSUE TITLE
ArgumentException for SerializableError ASP.NET Core type

### ISSUE THREAD

**Issue by SiggyBar** [dahomey-technologies/Dahomey.Json#42]
The premise is the same as in #41, but in this case there is an [ActionFilter](https://docs.microsoft.com/en-us/dotnet/api/microsoft.aspnetcore.mvc.filters.actionfilterattribute?view=aspnetcore-3.1) that sets a [BadRequestObjectResult](https://docs.microsoft.com/en-us/dotnet/api/microsoft.aspnetcore.mvc.badrequestobjectresult?view=aspnetcore-3.1).

Then I get a "500 Internal Server Error" with body:
```
System.ArgumentException: GenericArguments[0], 'System.Collections.Generic.Dictionary`2+KeyCollection[System.String,System.Object]', on 'Dahomey.Json.Serialization.Converters.CollectionConverter`2[TC,TI]' violates the constraint of type 'TC'.
---> System.TypeLoadException: GenericArguments[0], 'System.Collections.Generic.Dictionary`2+KeyCollection[System.String,System.Object]', on 'Dahomey.Json.Serialization.Converters.CollectionConverter`2[TC,TI]' violates the constraint of type parameter 'TC'.
   at System.RuntimeTypeHandle.Instantiate(Type[] inst)
   at System.RuntimeType.MakeGenericType(Type[] instantiation)
   --- End of inner exception stack trace ---
   at System.RuntimeType.ValidateGenericArguments(MemberInfo definition, RuntimeType[] genericArguments, Exception e)
   at System.RuntimeType.MakeGenericType(Type[] instantiation)
   at Dahomey.Json.Serialization.Converters.Factories.AbstractJsonConverterFactory.CreateGenericConverter(JsonSerializerOptions options, Type genericType, Type[] typeArguments) in z:\repos\dahomey.json\src\Dahomey.Json\Serialization\Converters\Factories\AbstractJsonConverterFactory.cs:line 23
   at Dahomey.Json.Serialization.Converters.Factories.CollectionConverterFactory.CreateConverter(Type typeToConvert, JsonSerializerOptions options) in z:\repos\dahomey.json\src\Dahomey.Json\Serialization\Converters\Factories\CollectionConverterFactory.cs:line 88
   at System.Text.Json.JsonSerializerOptions.GetConverter(Type typeToConvert)
   at Dahomey.Json.Serialization.Converters.Mappings.MemberMapping`1.InitializeConverter() in z:\repos\dahomey.json\src\Dahomey.Json\Serialization\Converters\Mappings\MemberMapping.cs:line 144
   at Dahomey.Json.Serialization.Converters.Mappings.MemberMapping`1.GenerateMemberConverter() in z:\repos\dahomey.json\src\Dahomey.Json\Serialization\Converters\Mappings\MemberMapping.cs:line 93
   at Dahomey.Json.Serialization.Converters.ObjectConverter`1.MemberConverters.Create(JsonSerializerOptions options, IObjectMapping objectMapping) in z:\repos\dahomey.json\src\Dahomey.Json\Serialization\Converters\ObjectConverter.cs:line 46
   at Dahomey.Json.Serialization.Converters.ObjectConverter`1.<>c__DisplayClass14_0.<.ctor>b__0() in z:\repos\dahomey.json\src\Dahomey.Json\Serialization\Converters\ObjectConverter.cs:line 89
   at System.Lazy`1.ViaFactory(LazyThreadSafetyMode mode)
   at System.Lazy`1.ExecutionAndPublication(LazyHelper executionAndPublication, Boolean useDefaultConstructor)
   at System.Lazy`1.CreateValue()
   at System.Lazy`1.get_Value()
   at Dahomey.Json.Serialization.Converters.ObjectConverter`1.Write(Utf8JsonWriter writer, T value, JsonSerializerOptions options) in z:\repos\dahomey.json\src\Dahomey.Json\Serialization\Converters\ObjectConverter.cs:line 497
   at System.Text.Json.JsonPropertyInfoNotNullable`4.OnWrite(WriteStackFrame& current, Utf8JsonWriter writer)
   at System.Text.Json.JsonPropertyInfo.Write(WriteStack& state, Utf8JsonWriter writer)
   at System.Text.Json.JsonSerializer.Write(Utf8JsonWriter writer, Int32 originalWriterDepth, Int32 flushThreshold, JsonSerializerOptions options, WriteStack& state)
   at System.Text.Json.JsonSerializer.WriteAsyncCore(Stream utf8Json, Object value, Type inputType, JsonSerializerOptions options, CancellationToken cancellationToken)
   at Microsoft.AspNetCore.Mvc.Formatters.SystemTextJsonOutputFormatter.WriteResponseBodyAsync(OutputFormatterWriteContext context, Encoding selectedEncoding)
   at Microsoft.AspNetCore.Mvc.Formatters.SystemTextJsonOutputFormatter.WriteResponseBodyAsync(OutputFormatterWriteContext context, Encoding selectedEncoding)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeNextResultFilterAsync>g__Awaited|29_0[TFilter,TFilterAsync](ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Rethrow(ResultExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.ResultNext[TFilter,TFilterAsync](State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.InvokeResultFilters()
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeNextResourceFilter>g__Awaited|24_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Rethrow(ResourceExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.InvokeFilterPipelineAsync()
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Logged|17_1(ResourceInvoker invoker)
   at Microsoft.AspNetCore.Routing.EndpointMiddleware.<Invoke>g__AwaitRequestTask|6_0(Endpoint endpoint, Task requestTask, ILogger logger)
   at Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware.Invoke(HttpContext context)
```

I have narrowed the problem down to this example that uses the [SerializableError](https://docs.microsoft.com/en-us/dotnet/api/microsoft.aspnetcore.mvc.serializableerror?view=aspnetcore-3.1) class:

```C#
JsonSerializerOptions options = new JsonSerializerOptions();
//options.SetupExtensions();

object value = new SerializableError();

string result = JsonSerializer.Serialize(value, value.GetType(), options);
```

When I run this code, `result` will have the expected value of `{}`. However, when I comment in `options.SetupExtensions();`, then the Serialize() call throws the same exception as above. I would not expect calling SetupExtensions() to make a difference here.

**Comment by SiggyBar** [comment]
This works great now, thank you! 😄
