### ISSUE TITLE
Serialize a object that constructor types does not match 

### ISSUE THREAD

**Issue by feitzi** [dahomey-technologies/Dahomey.Json#56]
This code breaks with an exception:
```csharp
public class Car
    {
        public string Color { get;  }
        public int? Age { get;  }

        public Car(string color, string age)
        {
            Color = color;
            Age = int.Parse(age);
        }
    }

    class Program
    {
        static void Main(string[] args)
        {
            var options = new JsonSerializerOptions();
            options.SetupExtensions();

            var jsonString = System.Text.Json.JsonSerializer.Serialize(new Car("red", "4"), options);
            Console.WriteLine(jsonString);
        }
    }
```
Exception:
```
System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation.
 ---> System.Text.Json.JsonException: Type mismatch between creator argument and field or property named age on type JsonSerializer.Car
   at Dahomey.Json.Serialization.Converters.Mappings.CreatorMapping.Initialize()
   at Dahomey.Json.Serialization.Converters.Mappings.ObjectMapping`1.Initialize()
   at Dahomey.Json.Serialization.Converters.Mappings.ObjectMappingRegistry.CreateDefaultObjectMapping(Type type)
   at Dahomey.Json.Serialization.Converters.Mappings.ObjectMappingRegistry.<>c__DisplayClass7_0.<Lookup>b__0(Type t)
   at System.Collections.Concurrent.ConcurrentDictionary`2.GetOrAdd(TKey key, Func`2 valueFactory)
   at Dahomey.Json.Serialization.Converters.Mappings.ObjectMappingRegistry.Lookup(Type type)
   at Dahomey.Json.Serialization.Converters.Mappings.ObjectMappingRegistry.Lookup[T]()
   at Dahomey.Json.Serialization.Converters.ObjectConverter`1..ctor(JsonSerializerOptions options)
   --- End of inner exception stack trace ---
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor, Boolean wrapExceptions)
   at System.Reflection.RuntimeConstructorInfo.Invoke(BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at System.RuntimeType.CreateInstanceImpl(BindingFlags bindingAttr, Binder binder, Object[] args, CultureInfo culture)
   at System.Activator.CreateInstance(Type type, BindingFlags bindingAttr, Binder binder, Object[] args, CultureInfo culture, Object[] activationAttributes)
   at System.Activator.CreateInstance(Type type, Object[] args)
   at Dahomey.Json.Serialization.Converters.Factories.AbstractJsonConverterFactory.CreateConverter(JsonSerializerOptions options, Type converterType)
   at Dahomey.Json.Serialization.Converters.Factories.AbstractJsonConverterFactory.CreateGenericConverter(JsonSerializerOptions options, Type genericType, Type[] typeArguments)
   at Dahomey.Json.Serialization.Converters.Factories.ObjectConverterFactory.CreateConverter(Type typeToConvert, JsonSerializerOptions options)
   at System.Text.Json.JsonSerializerOptions.GetConverter(Type typeToConvert)
   at System.Text.Json.JsonClassInfo.GetClassType(Type type, JsonSerializerOptions options)
   at System.Text.Json.JsonClassInfo..ctor(Type type, JsonSerializerOptions options)
   at System.Text.Json.JsonSerializerOptions.GetOrAddClass(Type classType)
   at System.Text.Json.WriteStackFrame.Initialize(Type type, JsonSerializerOptions options)
   at System.Text.Json.JsonSerializer.WriteCore(Utf8JsonWriter writer, Object value, Type type, JsonSerializerOptions options)
   at System.Text.Json.JsonSerializer.WriteCore(PooledByteBufferWriter output, Object value, Type type, JsonSerializerOptions options)
   at System.Text.Json.JsonSerializer.WriteCoreString(Object value, Type type, JsonSerializerOptions options)
   at System.Text.Json.JsonSerializer.Serialize[TValue](TValue value, JsonSerializerOptions options)
   at JsonSerializer.Program.Main(String[] args) in C:\sources\JsonSerializer\JsonSerializer\Program.cs:line 28
```

The problem just exists if there are a constructor and a property with the same name (case insensitive) and a different type. If I change the type of `age` to `ageSomething` than the serializations works.

I just need serialization! 

Any ideas how I can fix that without change my whole constructor names?

**Comment by mcatanzariti** [comment]
Hi @feitzi 

I made a fix to support serializable only classes when no suitable constructors are found.
But you need to tell the framework not to use your constructor by reseting the "creator mapping":

```csharp
var options = new JsonSerializerOptions().SetupExtensions();
options.GetObjectMappingRegistry().Register<Car>(objectMapping =>
    objectMapping
        .AutoMap()
        .SetCreatorMapping(null)
);
var jsonString = JsonSerializer.Serialize(new Car("red", "4"), options);
```

**Comment by xperiandri** [comment]
@mcatanzariti that is a very very bad issue.
Why is it even matter for serialization?
I tried to serialize this class and it does not work
```
type AllowedGroupRequierment (groups : string seq) =
    member val Groups = groups.ToImmutableHashSet ()
    interface IAuthorizationRequirement
```
And I cannot exclude it, because this class is declared later than JSON configuration. And in F# you cannot use it before declared.

**Comment by xperiandri** [comment]
Ah, I've got it!
``` F#
type AllowedGroupRequierment (groups : string seq) =
    member val Groups = groups.ToImmutableHashSet ()
    interface IAuthorizationRequirement
```
It is because `groups` is `IEnumerable<string>` but `Groups` property is `ImmutableHashSet<string>`
