### ISSUE TITLE
Exception on non registered type

### ISSUE THREAD

**Issue by EngineerCoding** [dahomey-technologies/Dahomey.Json#68]
Hi,

I am using Dahomey.Json within an ASP.NET Core project as the main serializer. When I am serializing an entity which is not registered at all, I get the following exception:

```
System.InvalidOperationException: Method may only be called on a Type for which Type.IsGenericParameter is true.
   at System.RuntimeType.get_DeclaringMethod()
   at Dahomey.Json.Serialization.Converters.MemberConverter`2.Write(Utf8JsonWriter writer, Object obj, JsonSerializerOptions options)
   at Dahomey.Json.Serialization.Converters.ObjectConverter`1.Write(Utf8JsonWriter writer, T value, JsonSerializerOptions options)
   at Dahomey.Json.Serialization.Converters.MemberConverter`2.Write(Utf8JsonWriter writer, Object obj, JsonSerializerOptions options)
   at Dahomey.Json.Serialization.Converters.ObjectConverter`1.Write(Utf8JsonWriter writer, T value, JsonSerializerOptions options)
   at Dahomey.Json.Serialization.Converters.AbstractCollectionConverter`2.Write(Utf8JsonWriter writer, TC value, JsonSerializerOptions options)
   at System.Text.Json.Serialization.JsonConverter`1.TryWrite(Utf8JsonWriter writer, T& value, JsonSerializerOptions options, WriteStack& state)
   at System.Text.Json.Serialization.JsonConverter`1.WriteCore(Utf8JsonWriter writer, T& value, JsonSerializerOptions options, WriteStack& state)
   at System.Text.Json.Serialization.JsonConverter`1.WriteCoreAsObject(Utf8JsonWriter writer, Object value, JsonSerializerOptions options, WriteStack& state)
   at System.Text.Json.JsonSerializer.WriteCore[TValue](JsonConverter jsonConverter, Utf8JsonWriter writer, TValue& value, JsonSerializerOptions options, WriteStack& state)
   at System.Text.Json.JsonSerializer.WriteAsyncCore[TValue](Stream utf8Json, TValue value, Type inputType, JsonSerializerOptions options, CancellationToken cancellationToken)
   at Microsoft.AspNetCore.Mvc.Formatters.SystemTextJsonOutputFormatter.WriteResponseBodyAsync(OutputFormatterWriteContext context, Encoding selectedEncoding)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeNextResultFilterAsync>g__Awaited|29_0[TFilter,TFilterAsync](ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Rethrow(ResultExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.ResultNext[TFilter,TFilterAsync](State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.InvokeResultFilters()
--- End of stack trace from previous location ---
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeNextResourceFilter>g__Awaited|24_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Rethrow(ResourceExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeFilterPipelineAsync>g__Awaited|19_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Logged|17_1(ResourceInvoker invoker)
   at Microsoft.AspNetCore.Routing.EndpointMiddleware.<Invoke>g__AwaitRequestTask|6_0(Endpoint endpoint, Task requestTask, ILogger logger)
   at Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware.Invoke(HttpContext context)
```

I am using the following to use this serializer within ASP.NET Core

```
services.AddControllersWithViews()
                .AddJsonOptions(jsonOptions =>
                {
                    // Used for polymorhphism during serialization and deserialization
                    jsonOptions.JsonSerializerOptions.SetupExtensions();
                    DiscriminatorConventionRegistry registry = jsonOptions.JsonSerializerOptions.GetDiscriminatorConventionRegistry();
                    registry.ClearConventions();
                    registry.RegisterConvention(new DefaultDiscriminatorConvention<byte>(jsonOptions.JsonSerializerOptions, nameof(IDiscriminator.Type))); // Importantin thing it uses the "Type" property
                    registry.RegisterType<AnotherSuperType>();
                    registry.RegisterType<SomeSuperType>();
                });
```

**Comment by mcatanzariti** [comment]
Please, can you provide the definition of the class you are trying to serializer?

**Comment by mcatanzariti** [comment]
Please, feel free to reopen this issue, once you will have provided the definition of the class you are trying to serialize.
